// 模擬資料，當 Supabase 未設定時使用

export const mockShoes = [
  {
    id: '1',
    name: 'Speedgoat 5',
    brand: 'HOKA',
    stack_height: 32,
    drop: 4,
    lug_depth: 5,
    weight: 310,
    image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop',
    short_desc: '經典越野跑鞋，適合各種地形',
    description: 'Speedgoat 5 是 HOKA 的經典越野跑鞋，採用 Vibram Megagrip 大底，提供優異的抓地力。適合長距離越野跑和技術性路線。',
    pros: ['優異的抓地力', '舒適的緩震', '耐用的大底'],
    cons: ['價格較高', '重量稍重'],
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Ultraventure 3',
    brand: 'HOKA',
    stack_height: 33,
    drop: 5,
    lug_depth: 4,
    weight: 295,
    image_url: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=300&fit=crop',
    short_desc: '輕量長距離越野跑鞋',
    description: 'Ultraventure 3 專為長距離越野跑設計，輕量化設計讓您跑得更遠更輕鬆。',
    pros: ['輕量化', '長距離舒適', '透氣性佳'],
    cons: ['抓地力一般', '緩震較少'],
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Peregrine 13',
    brand: 'Saucony',
    stack_height: 28,
    drop: 4,
    lug_depth: 5.5,
    weight: 285,
    image_url: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=300&fit=crop',
    short_desc: '靈活敏捷的越野跑鞋',
    description: 'Peregrine 13 提供靈活的腳感和優異的抓地力，適合技術性路線和快速訓練。',
    pros: ['靈活敏捷', '優異抓地力', '價格合理'],
    cons: ['緩震較少', '耐用性一般'],
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Mountain Racer 4',
    brand: 'Topo',
    stack_height: 25,
    drop: 0,
    lug_depth: 4.5,
    weight: 250,
    image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop',
    video_url: '/videos/解構_Topo_MTN_Racer_4.mp4',
    slides: [
      '/slides/topo-mtn-racer-4/topo-mtn-racer-4-01.png',
      '/slides/topo-mtn-racer-4/topo-mtn-racer-4-02.png',
      '/slides/topo-mtn-racer-4/topo-mtn-racer-4-03.png',
      '/slides/topo-mtn-racer-4/topo-mtn-racer-4-04.png',
      '/slides/topo-mtn-racer-4/topo-mtn-racer-4-05.png',
      '/slides/topo-mtn-racer-4/topo-mtn-racer-4-06.png',
      '/slides/topo-mtn-racer-4/topo-mtn-racer-4-07.png',
      '/slides/topo-mtn-racer-4/topo-mtn-racer-4-08.png',
      '/slides/topo-mtn-racer-4/topo-mtn-racer-4-09.png',
      '/slides/topo-mtn-racer-4/topo-mtn-racer-4-10.png',
      '/slides/topo-mtn-racer-4/topo-mtn-racer-4-11.png',
      '/slides/topo-mtn-racer-4/topo-mtn-racer-4-12.png',
      '/slides/topo-mtn-racer-4/topo-mtn-racer-4-13.png',
      '/slides/topo-mtn-racer-4/topo-mtn-racer-4-14.png',
      '/slides/topo-mtn-racer-4/topo-mtn-racer-4-15.png',
    ],
    short_desc: '零落差輕量競速越野跑鞋',
    description: 'Topo Mountain Racer 4 是一款零落差的輕量競速越野跑鞋，專為追求速度的跑者設計。採用 Vibram Megagrip 大底，提供優異的抓地力和靈活性。',
    pros: ['零落差設計', '輕量化', '優異抓地力', '靈活敏捷'],
    cons: ['緩震較少', '需要適應期'],
    created_at: new Date().toISOString(),
  },
]

export const mockReviews = {
  '1': [
    {
      id: 'r1',
      shoe_id: '1',
      user_id: 'user1',
      user_name: '測試使用者',
      user_photo: null,
      content: '這雙鞋的抓地力真的很棒！在濕滑的路面上也能穩定跑步。',
      created_at: new Date(Date.now() - 86400000).toISOString(),
    },
  ],
}

